# 开发环境配置
server:
  # 服务端口
  port: 9081
  servlet:
    # 项目contextPath
    context-path: /material
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  # 數據源配置
  datasource:
    #配置驅動
    driver-class-name: com.mysql.cj.jdbc.Driver
    #本地
    url: jdbc:mysql://localhost:3306/fen?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 

    
  #開啓切麵編程
  aop:
    auto: true
  #加載靜態資源
  resources:
    static-locations: classpath:/resources/,classpath:/static/


  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 文件上传
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
      
  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-wait: 30000
        max-active: 600
        max-idle: 300
        min-idle: 100
    timeout: 2500
      
      
#MyBatis
mybatis-plus:
  #mapper扫描
  mapper-locations: classpath*:/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #去除mybatis-plus的logo
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #不加这个查询数据为空时，字段将被隐藏
call-setters-on-nulls: true


#日志打印
logging:
  file:
    path: D:/log/spider/
  level:
    com:
      system:
        mapper: DEBUG